# Preparation

The last 12 months to-date (as of February 27, 2023) of data from the fictional company, "Cyclistic", have been collected.

See data resource [here](https://divvy-tripdata.s3.amazonaws.com/index.html)

While downloading these data-sets, I've taken quick looks at each file through excel just to get an idea of what each data-set consisted of. I found that each data-set share the same amount of columns as well as the column names which happen to be self explanatory and need not further documentation as to what each column represents. I also noticed that each data-set contains more than 100,000 rows of data. Considering there are 12 separate data-sets, combining all of them through excel would be insufficient for reasons being that Microsoft Excel has a maximum row limit of 1,048,576.

So before importing these files directly to BigQuery, I'll conduct my first couple steps of data manipulation just to add more context to the data.

I will execute the following through excel:

1.  Create new column 'ride_length' by subtracting 'started_at' from 'ended_at'

2.  Create new column 'day_of_week' by using the WEEKDAY command (1=Sunday and 7=Saturday)

Although more evaluation needs to happen, I wanted to bind all the data-frames (not merge) so that I can clean the data at a larger scale instead of cleaning each data-frame individually.

Next step for me is to determine how many missing values there are and how to deal with them.

#### NOTES BEFORE ENDED SESSION:

What is the significance of determining how to fill the missing values for station start and end names? What columns and data should be a priority? Are station IDs just as valuable as station names?

------------------------------------------------------------------------

#### Continued..

After further reviewing the missing values, I noticed that majority of the missing values are located within the start_station and end_station, names and IDs. Imputing the missing values would need further work and perhaps machine learning techniques. However for data analysis, there are still some important feature columns that can still provide insightful results.

So going forward, I will be taking out the columns that include the start and end location data, and I will just focus on the time, length, membership type and ride type.

Final data made. Now for analysis.

# Analysis

Business problem reminder: The director of marketing believes the company's future success depends on maximizing the number of annual memberships. The objective is to prove or disprove this theory by finding the distinction between casual and annual memberships.

For comparisons and contrast, I will resume my analysis on Tableau! Tableau will allow me to conveniently visualize the data that makes sense to the objective.

I will summarize the context and findings of the visualizations in Tableau.And I will also take note of the visualizations here in my RStudio Documentation tab.

##### Tableau Sheet "Average Minutes":

Average amount of minutes casuals and membership riders ride throughout the year. Casual Members average 4-6 minutes more of riding then membership riders. Casual riders tend to spend more time on the bikes than membership riders.

##### Tableau Sheet "Daily Ride Activity":

Daily Activity for each month. Riders with memberships are more active monday-friday with activity spikes of about 10k more riders riding tuesday-thursday.

Casual riders with no membership are more active on weekends with dips in activity from Sunday to Monday and spikes back up from Friday to Saturday. The company is experiencing dips and spikes of about 20k - 30k rides every week for casual riders.

##### Tableau Sheet "Bike Type":

This sheet shows a visualization of what type of bikes are used between casual riders and membership riders. Members use electric bikes as much as they use classic bikes with 1.7M membership riders using classic and 1.6M membership riders using electric.

Casual riders tend to ride the electric bikes more than the classic bikes with 1.2M riders using electric and 900K riders using classic bikes.

##### Tableau Sheet "Hour of Day Active":

Stacked bar chart showing both casual and membership rider activity for each hour throughout the day. Normal distribution of activity for both members and casual riders imply that there is little difference between what hours of the day riders are active.

Membership riders have a slight spike bigger than casual riders around 8am.

##### Tableau Sheet "Membership/Casual Count":

This pie chart shows the percentage of both casual and membership riders that make up the whole clientele. 41% of riders are casual and 59% of riders have a membership out of a total of 5.75M riders.

## Recommendations

One of the ways Cyclistic markets their bikes is by offering single-ride passes and full-day passes. Without data on how often and to what extent these passes are purchased, we can potentially miss out on information that help us better understand the casual segment.

Cyclistic sets itself apart by offering a variety of other bikes like reclining bikes, hand tricycles, and cargo bikes which can help people with disabilities and/or don't know how to use a standard two-wheeled bike. We know that 8% of Cyclistic riders use the assistive options. By focusing on the quality of rides for these assisted riders, we can potentially broaden and welcome more riders and offer a special discounted price for them.
