# Preparation

------------------------------------------------------------------------

## Libraries

```{r}
library(readr)
library(tibble)
library(tidyr)
library(tidyverse)
```

Import necessary data-sets\
*each data-set has new columns added 'ride_length' and 'day_of_week'*\
Past 12 months of bike trip data:

```{r}
jan_tripdata2023 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/jan-tripdata2023.csv")
dec_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/dec-tripdata2022.csv")
nov_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/nov-tripdata2022.csv")
oct_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/oct-tripdata2022.csv")
sept_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/sept-tripdata2022.csv")
aug_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/aug-tripdata2022.csv")
july_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/july-tripdata2022.csv")
june_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/june-tripdata2022.csv")
may_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/may-tripdata2022.csv")
april_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/april-tripdata2022.csv")
march_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/march-tripdata2022.csv")
feb_tripdata2022 <- read_csv("Local-repo-only/Cyclistic-tripdata-past12months/feb-tripdata2022.csv")
```

Combining all data-sets into one data-frame:

```{r}
DF = do.call("rbind", list(jan_tripdata2023,dec_tripdata2022,nov_tripdata2022,oct_tripdata2022,sept_tripdata2022,aug_tripdata2022,july_tripdata2022,june_tripdata2022,may_tripdata2022,april_tripdata2022,march_tripdata2022,feb_tripdata2022))
```

```{r}
head(DF)
```

```{r}
unique_values_end_station <- unique(DF$end_station_name)
```

```{r}
view(unique_values_end_station)
```

```{r}
len(unique_values_end_station)
```

```{r}
DF_Unique1 <- DF %>%
  group_by(start_station_name)%>%
  filter(start_lat == 41.80000 & start_lng == -87.62000)
```

```{r}
DF_Unique1_filtered <- (DF_Unique1$start_station_name)
```

```{r}
view(DF_Unique1_filtered)
```

```{r}
table(DF_Unique1$start_station_name, useNA = "ifany")
```

```{r}
sum(is.na(DF))
```

```{r}
library(ggmice)
```

```{r}
round(colSums(is.na(DF))/ nrow(DF),2)
```

```{r}
browseVignettes(package = 'ggmice')
```

```{r}
help(plot_pattern)
```

```{r}
plot_pattern(DF)
```
